### PR TITLE
Fix htonll check for OSX Yosemite

### LINKED ISSUE #862: Master doesn't compile on Mac OS X
Currently, when trying to build Master on Mac OS X, I get: 

```
cpu.c:235:2: error: use of undeclared identifier 'cpu_temp_retry_max'
        cpu_temp_retry_max = 86400 / CDTIME_T_TO_TIME_T (plugin_get_interval ());
        ^
```

(actually I can't really find that defined anywhere, either)...

### LINKED ISSUE #884: collectd-5.3 branch fails to compile on OSX (Yosemite)
Running:
```
git checkout origin/collectd-5.3
./clean.sh
./build.sh
./configure
make
```

`make` fails:

```
In file included from perl.c:36:
./daemon/collectd.h:106:13: error: cannot combine with previous 'int' declaration specifier
typedef int _Bool;
            ^
./daemon/collectd.h:192:3: error: "Cannot determine byte order"
# error "Cannot determine byte order"
  ^
./daemon/collectd.h:106:1: error: typedef requires a name [-Werror,-Wmissing-declarations]
typedef int _Bool;
^~~~~~~~~~~~~~~~~
./daemon/collectd.h:308:9: error: unknown type name 'uint64_t'
typedef uint64_t cdtime_t;
        ^
In file included from perl.c:62:
./daemon/common.h:296:20: error: expected ')'
unsigned long long ntohll (unsigned long long n);
                   ^
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^

...
```

[full gist](https://gist.github.com/ryan-williams/a4ac719c6461b29557ce)

Forked from #862 as these failures crop up after the top-level failure there is fixed (by 9f5ea03c55ef747c63a258e7abdbbf07a3b1bbf7)

### PR DESCRIPTION
**Pull request by ryan-williams**
fixes #884 (and would presumably further fix #862 once 9f5ea03c55ef747c63a258e7abdbbf07a3b1bbf7 was merged into `master`).

I'm filing this against `origin/collectd-5.3` since that seems like the most recently active branch; let me know if I should file it against a different branch instead, e.g. `origin/collectd-5.4`.

A few notes on this fix:
* I have no idea why `autoconf` seems to require double-square-brackets in the `htonll` check `AC_LANG_PROGRAM`.
* I inferred that this fix would work because:
  * I noticed that my `./configure` runs on OSX Yosemite were [erroneously failing to find `htonll` installed on my system](https://gist.github.com/ryan-williams/a4ac719c6461b29557ce#file-gistfile1-txt-L609).
  * Inspecting [my `config.log`](https://gist.github.com/ryan-williams/11172badc03a9e827b28#file-config-log), I noticed that the `htonll` test program was failing on what seemed to be stray [open-](https://gist.github.com/ryan-williams/11172badc03a9e827b28#file-config-log-L16357-L16361) and [close-](https://gist.github.com/ryan-williams/11172badc03a9e827b28#file-config-log-L16357-L16361) square-brackets.
  * Indeed, the `AC_LANG_PROGRAM`-generated test-program [seemed to have an extra set of square-brackets quoting its "prologue" and "body" sections](https://gist.github.com/ryan-williams/11172badc03a9e827b28#file-config-log-L16546-L16563):
  ```
  | [
  | #include <sys/types.h>
  | #include <netinet/in.h>
  | #if HAVE_INTTYPES_H
  | # include <inttypes.h>
  | #endif
  | ]
  | int
  | main ()
  | {
  | [
  |           return htonll(0);
  | ]
  | 
  |   ;
  |   return 0;
  | }
  configure:18820: result: no
  ```

So I am reasonably confident that this is a sane fix to the problem, though I have very little idea why it was necessary. I verified that compilation of `origin/collectd-5.3` (ba55ad9ae41052b665d008f20f4b7076983446e2) works on OSX Yosemite as well as on a CentOS 6.6 box I have laying around.

### CODE REVIEW

**Comment by mfournier** [comment]
@ryan-williams so it appears I screw up and only merged #591 to collectd-5.4, not collectd-5.3. I just cherry-picked the patch to 5.3 now.

#350 and #541 have details on the reason behind these triple brackets.

Also, I just merged all the bugfix branches to master, so a bunch of bugfixes (including 9f5ea03) is now in master. Can you please give another try to the master and collectd-5.3 branches on Yosemite now and let us know how it goes ? Thanks !

**Comment by ryan-williams** [comment]
ah, thanks for the info @mfournier.

I am still seeing `make` errors on `origin/master` (ca316d91e178412604ea8462dc60a8bc32cbfc87):

```
  CC       perl_la-perl.lo
In file included from perl.c:36:
./daemon/collectd.h:106:13: error: cannot combine with previous 'int' declaration specifier
typedef int _Bool;
            ^
./daemon/collectd.h:192:3: error: "Cannot determine byte order"
# error "Cannot determine byte order"
  ^
./daemon/collectd.h:106:1: error: typedef requires a name [-Werror,-Wmissing-declarations]
typedef int _Bool;
^~~~~~~~~~~~~~~~~
./daemon/collectd.h:308:9: error: unknown type name 'uint64_t'
typedef uint64_t cdtime_t;
        ^
In file included from perl.c:62:
./daemon/common.h:296:20: error: expected ')'
unsigned long long ntohll (unsigned long long n);
                   ^
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
./daemon/common.h:296:20: note: to match this '('
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
In file included from perl.c:62:
./daemon/common.h:296:20: error: conflicting types for '__builtin_constant_p'
unsigned long long ntohll (unsigned long long n);
                   ^
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:6: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
     ^
./daemon/common.h:296:20: note: '__builtin_constant_p' is a builtin with type 'int ()'
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:6: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
     ^
In file included from perl.c:62:
./daemon/common.h:297:20: error: expected ')'
unsigned long long htonll (unsigned long long n);
                   ^
/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
./daemon/common.h:297:20: note: to match this '('
/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
In file included from perl.c:62:
./daemon/common.h:297:20: error: conflicting types for '__builtin_constant_p'
unsigned long long htonll (unsigned long long n);
                   ^
/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:6: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
     ^
./daemon/common.h:296:20: note: '__builtin_constant_p' is a builtin with type 'int ()'
unsigned long long ntohll (unsigned long long n);
                   ^
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:6: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
     ^
In file included from perl.c:62:
./daemon/common.h:307:3: error: "Don't know how to convert between host and network representation of doubles."
# error "Don't know how to convert between host and network representation of doubles."
  ^
9 errors generated.
```
[full gist](https://gist.github.com/ryan-williams/14db26e0b529b65cdecc)

**Comment by ryan-williams** [comment]
fwiw latest `origin/collectd-5.3` (443afcad2cbacaca9bb1fd7d9ea790cbeb6ff015) seems to work!

**Comment by ryan-williams** [comment]
likewise `origin/collectd-5.4` (ecbcaadde7dff838f09dfb04c7eb90f126e35abf) works.

not obvious to me why `origin/master` would not work with those two merged in, but I don't have as good of a sense of what branches include what as you do, so I'll defer to you

**Comment by ryan-williams** [comment]
going to close this out in the meantime since it was apparently redundant
