### ISSUE TITLE
python plugin: unable to compile with python 2.4

### ISSUE THREAD

**Issue by rubenk** [collectd/collectd#1863]
```
python.c: In function 'cpy_write_callback':
python.c:456: error: 'Values' has no member named 'ob_refcnt'
make[3]: *** [python_la-python.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory `/home/ruben/src/collectd/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/ruben/src/collectd/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/ruben/src/collectd/src'
make: *** [all-recursive] Error 1
```

We could fix this, but I wouldn't mind if we bumped the minimum required python version to 2.6 instead.

@trenkel what do you think?

**Comment by trenkel** [comment]
Ah, I see the problem. From the Python source code, Include/object.py:

Version 2.5:
#define Py_DECREF(op)					\
	if (_Py_DEC_REFTOTAL  _Py_REF_DEBUG_COMMA	\
	    --(op)->ob_refcnt != 0)			\
		_Py_CHECK_REFCNT(op)			\
	else						\
_Py_Dealloc((PyObject *)(op))

Version 2.6:
#define Py_DECREF(op)                                   \
    if (_Py_DEC_REFTOTAL  _Py_REF_DEBUG_COMMA           \
        --((PyObject*)(op))->ob_refcnt != 0)                    \
        _Py_CHECK_REFCNT(op)                            \
    else                                                \
_Py_Dealloc((PyObject *)(op))

Notice the cast to PyObject in 2.6. But when I wrote this in 2009 the stable Debian version was Lenny, which shipped with Python 2.5, so how did that ever work in the first place? Simple, by having a memory leak and never freeing that object. This was only fixed in https://github.com/collectd/collectd/commit/e1da538180881c6dcc1d686e504128327a1f56b9 in 2012. So we haven't been compatible with Python 2.3 to 2.5 for 4 years now. Which means there's probably no point in investing energy of fixing this. It also means we can delete a bunch of macros from cpython.h that exist just to make it work with Python 2.3.

**Comment by rubenk** [comment]
Heh, nice one!

I caught this on RHEL5, which still has Python 2.4, but also Python 2.6 from EPEL (which is what we use on the builders.

> So we haven't been compatible with Python 2.3 to 2.5 for 4 years now.

And no one  complained afaik.
