### ISSUE TITLE
collectd-5.3 branch fails to compile on OSX (Yosemite)

### ISSUE THREAD

**Issue by ryan-williams** [collectd/collectd#884]
Running:
```
git checkout origin/collectd-5.3
./clean.sh
./build.sh
./configure
make
```

`make` fails:

```
In file included from perl.c:36:
./daemon/collectd.h:106:13: error: cannot combine with previous 'int' declaration specifier
typedef int _Bool;
            ^
./daemon/collectd.h:192:3: error: "Cannot determine byte order"
# error "Cannot determine byte order"
  ^
./daemon/collectd.h:106:1: error: typedef requires a name [-Werror,-Wmissing-declarations]
typedef int _Bool;
^~~~~~~~~~~~~~~~~
./daemon/collectd.h:308:9: error: unknown type name 'uint64_t'
typedef uint64_t cdtime_t;
        ^
In file included from perl.c:62:
./daemon/common.h:296:20: error: expected ')'
unsigned long long ntohll (unsigned long long n);
                   ^
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^

...
```

[full gist](https://gist.github.com/ryan-williams/a4ac719c6461b29557ce)

Forked from #862 as these failures crop up after the top-level failure there is fixed (by 9f5ea03c55ef747c63a258e7abdbbf07a3b1bbf7)

**Comment by ryan-williams** [comment]
this appears to be resolved as of 443afcad2cbacaca9bb1fd7d9ea790cbeb6ff015
