### PR TITLE
[ci][cirrus] Replace trusty with bionic/focal in debian_default_toolchain

### PR DESCRIPTION
**Pull request by elfiesmelfie**
Ubuntu 14.04 (Trusty) is out of standard support [1].
``make check`` fails for test_capabilities, as noted in [2].
[3] indicates that the cause is glibc, but that updates are not expected
to the version in trusty.

This PR replaces trusty with Ubuntu 18.04 (Bionic) and 20.04 (Focal).

[1] https://wiki.ubuntu.com/Releases
[2] https://github.com/collectd/collectd/pull/3936
[3] https://github.com/collectd/collectd/pull/3927#issuecomment-953350598

### CODE REVIEW

**Comment by mrunge** [comment]
Thank you for working on this.

debian_default_toolchain container:collectd/ci:focal_amd64 Failing after 16m — Task Summary

```
Failed to start an instance! Failed to pull null image! Repository does not exist or may require authentication.
```

**Comment by elfiesmelfie** [comment]
This one's on me, I forgot to confirm that the focal container merged: https://github.com/collectd/ci-docker/pull/39

I'll have a look at that when I get a chance, and will either resolve the changes needed to merge or remove focal from cirrus for now

**Comment by elfiesmelfie** [comment]
> This one's on me, I forgot to confirm that the focal container merged: [collectd/ci-docker#39](https://github.com/collectd/ci-docker/pull/39)
> 
> I'll have a look at that when I get a chance, and will either resolve the changes needed to merge or remove focal from cirrus for now
 Thanks for merging [collectd/ci-docker#39](https://github.com/collectd/ci-docker/pull/39)

I also forgot I needed to propose this one to get the image built weekly: https://github.com/collectd/ci-docker/pull/51

**Comment by mrunge** [comment]
Thank you, this makes sense to me.

Focal failing during tests is not related to this.

**Review by mrunge — APPROVED** [review]

**Comment by mrunge** [comment]
Thank you, looks good to me. Can you please rebase the branch?

**Comment by mrunge** [comment]
Intel RDT fails to build because of a warning
```
src/intel_rdt.c: In function 'rdt_config':
src/intel_rdt.c:1220:3: error: implicit declaration of function 'rdt_config_events'; did you mean 'rdt_config_cgroups'? [-Werror=implicit-function-declaration]
   rdt_config_events(g_rdt);
   ^~~~~~~~~~~~~~~~~
   rdt_config_cgroups
 ```

**Comment by elfiesmelfie** [comment]
The ``rdt_config_events`` function is defined within a ``#ifdef LIBPQOS2`` block, but the call to the function is not guarded.
This looks like a likely cause of the issue.
 
The version in focal vs bionic are different, which explains why the error doesn't show up in focal. 

in bionic: 
```
# apt list --installed | grep -i intel-cmt-cat
intel-cmt-cat/bionic,now 1.2.0-1 amd64 [installed]
```

in focal:
```
# apt list --installed | grep -i intel-cmt-cat
intel-cmt-cat/focal,now 3.2-1 amd64 [installed]
```

**Comment by kwiatrox** [comment]
The issue with intel_rdt was introduced by #3774.
@aleksinx, @KubaTrojan, can you confirm that moving the function `rdt_config_events` outside of `#ifdef LIBPQOS2` block can fix the issue?

**Comment by paweltox** [comment]
Hi I've reproduced this error and I can confirm that moving rdt_config_events function out of #ifdef LIBPQOS2 makes it build correctly on Bionic.

**Comment by elfiesmelfie** [comment]
> I reproduced this error and I can confirm that moving rdt_config_events function out of #ifdef LIBPQOS2 makes it build correctly on Bionic.

I added a prelim change here: https://github.com/collectd/collectd/pull/3950
I think it's probably better to move the function definition, but please comment there. Unfortunately, there will be no bionic CI immediately, but I can update this PR to disable intel_rdt on bionic, and once it merges, I can rebase #3950 (or vice-verse)

**Comment by mrunge** [comment]
Can you please rebase this @elfiesmelfie ?

**Comment by paweltox** [comment]
I tried to reproduce this issue with virt tests failing on my local Ubuntu/Focal but unfortunately it doesn't fail. Where can I find test-suite.log file to see what exactly failed on CI?

**Comment by eero-t** [comment]
> I tried to reproduce this issue with virt tests failing on my local Ubuntu/Focal but unfortunately it doesn't fail. Where can I find test-suite.log file to see what exactly failed on CI?

Anybody?  I would also be interested about the full log for failures (and diff for format changes).  Having a CI fail without a proper log of what actually goes wrong is infuriating.

PS. Similar test container update is need also for v6 branch, as PRs for it are also failing with "trusty".

**Review by mrunge — APPROVED** [review]
This looks good for me. The test issues with the virt plugin should be treated separately. Trusty won't get us anywhere, it is unsupported and should not be used anymore.

**Comment by elfiesmelfie** [comment]
> > I tried to reproduce this issue with virt tests failing on my local Ubuntu/Focal but unfortunately it doesn't fail. Where can I find test-suite.log file to see what exactly failed on CI?
> 
> Anybody? I would also be interested about the full log for failures (and diff for format changes). Having a CI fail without a proper log of what actually goes wrong is infuriating.
> 
> PS. Similar test container update is need also for v6 branch, as PRs for it are also failing with "trusty".

Apologies for the late response. I agree that being able to see the logs is good. It's an oversight on my part that this was left out.
I could add a ``cat ./test-suite.log`` step if there's a failure, and see how much that helps. While the formatting/inelegance might leave a lot to be desired, it would be a clear improvement, and reduce the effort required to help debug an issue.
