### ISSUE TITLE
dns plugin does not compile on solaris 11 / sparc

### ISSUE THREAD

**Issue by xtra-be** [collectd/collectd#977]
master does not compile on solaris 11.2 / sparc
it breaks on the dns plugin 
Making all in daemon
  CC     utils_dns.lo
utils_dns.c: In function â€˜handle_ipv6â€™:
utils_dns.c:479:17: error: storage size of â€˜ext_hdrâ€™ isnâ€™t known
  struct ip6_ext ext_hdr;
                 ^
utils_dns.c:483:24: error: invalid application of â€˜sizeofâ€™ to incomplete type â€˜struct ip6_extâ€™
  if ((offset + sizeof (struct ip6_ext)) > (unsigned int)len)
                        ^
utils_dns.c:490:52: error: invalid application of â€˜sizeofâ€™ to incomplete type â€˜struct ip6_extâ€™
  memcpy (&ext_hdr, (char *) ipv6 + offset, sizeof (struct ip6_ext));
                                                    ^
utils_dns.c:479:17: error: unused variable â€˜ext_hdrâ€™ [-Werror=unused-variable]
  struct ip6_ext ext_hdr;
                 ^
cc1: all warnings being treated as errors
*** Error code 1
The following command caused the error:
echo "  CC    " utils_dns.lo;depbase=`echo utils_dns.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool --silent --tag=CC    --mode=compile gcc -DHAVE_CONFIG_H  -I.  -I./daemon -DPREFIX='"/opt/collectd"'  -DCONFIGFILE='"/opt/collectd/etc/collectd.conf"'  -DLOCALSTATEDIR='"/opt/collectd/var"'  -DPKGLOCALSTATEDIR='"/opt/collectd/var/lib/collectd"'  -DPIDFILE='"/opt/collectd/var/run/collectd.pid"' -DPLUGINDIR='"/opt/collectd/lib/collectd"'  -DPKGDATADIR='"/opt/collectd/share/collectd"'   -Wall -Werror -g -O2 -MT utils_dns.lo -MD -MP -MF $depbase.Tpo -c -o utils_dns.lo utils_dns.c &&\
mv -f $depbase.Tpo $depbase.Plo
make: Fatal error: Command failed for target `utils_dns.lo'

**Comment by octo** [comment]
Closing this in favour of #348.
