### ISSUE TITLE
Compiling from git on Mac OS X error: ‘MSG_NOSIGNAL’ undeclared

### ISSUE THREAD

**Issue by njh** [collectd/collectd#809]
Hello,

When compiling from Git on Mac OS X, I get the following error:

```
Making all in daemon
  CC       collectd-collectd.o
collectd.c: In function ‘notify_systemd’:
collectd.c:474: error: ‘MSG_NOSIGNAL’ undeclared (first use in this function)
collectd.c:474: error: (Each undeclared identifier is reported only once
collectd.c:474: error: for each function it appears in.)
```

`git blame` seems to think that this was introduced in ff270e6d53374bddca9f3fe0bb7a8c2294548edc by @pyr 

MSG_NOSIGNAL is not defined anywhere within /usr/include on Mac OS 10.8.5

nick.
