### PR TITLE
declare cpu_temp_retry_max in src/cpu.c to fix comp under clang (#862)

### PR DESCRIPTION
**Pull request by skottler**
This may be vaguely related to #862, but this makes master compile on 10.10 for me.

### CODE REVIEW

**Comment by skottler** [comment]
Without this patch:

```
cpu.c:160:2: error: use of undeclared identifier 'cpu_temp_retry_max'
        cpu_temp_retry_max = 86400 / CDTIME_T_TO_TIME_T (plugin_get_interval ());
        ^
1 error generated.
make[3]: *** [cpu_la-cpu.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```

**Comment by skottler** [comment]
This actually looks like line 160 in `cpu.c` was removed. Closing.
