### ISSUE TITLE
Problem compiling 5.4 with libstatgrab 0.9

### ISSUE THREAD

**Issue by bilsch** [collectd/collectd#445]
I ran in to an error while trying to recompile 5.4.0. Turns out, the error is likely related to an api change upstream in the libstatgrab api

We had previously been using libstatgrab 0.17. Starting in 0.90 they have changed their api. Here is the compile error:

```
gcc -DHAVE_CONFIG_H -I.  -DPREFIX='"/usr"' -DCONFIGFILE='"/etc/collectd.conf"' -DLOCALSTATEDIR='"/var"' -DPKGLOCALSTATEDIR='"/var/lib/collectd"' -DPIDFILE='"/var/run/collectd.pid"' -DPLUGINDIR='"/usr/lib64/collectd"' -DPKGDATADIR='"/usr/share/collectd"' -I../libltdl  -Wall -Werror  -DLT_LAZY_OR_NOW='RTLD_LAZY|RTLD_GLOBAL' -MT collectd-collectd.o -MD -MP -MF .deps/collectd-collectd.Tpo -c -o collectd-collectd.o `test -f 'collectd.c' || echo './'`collectd.c
collectd.c: In function 'do_init':
collectd.c:291: error: too few arguments to function 'sg_init'
make[3]: *** [collectd-collectd.o] Error 1
make[3]: Leaving directory `/local/wps23/rpmbuild/BUILD/collectd-5.4.0/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/local/wps23/rpmbuild/BUILD/collectd-5.4.0/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/local/wps23/rpmbuild/BUILD/collectd-5.4.0/src'
make: *** [all-recursive] Error 1
```

Link to the libstatgrab news site talking about an api change: http://www.i-scream.org/libstatgrab/#news

Re-running the compile with libstatgrab 0.17 works

**Comment by rubenk** [comment]
This seems to be fixed by 35d951756b0e05db90a7ce530fb7318917ab09ed. @bilsch can this issue be closed?

**Comment by bilsch** [comment]
@rubenk sorry I have not been responding on this. I don't have an environment to build / test this as I no longer work at the company I had found the issue with. I can set up something similar on my own network if you would like.

barring that, it looks like @vincentbernat has tested on linux and reported success. I'd say go ahead and close it.

**Comment by rubenk** [comment]
@bilsch no problem at all, thanks for replying.
