### PR TITLE
modbus plugin: Avoid sizeof(struct sockaddr).

### PR DESCRIPTION
**Pull request by octo**
The previous version failed on FreeBSD with:

    modbus.c: In function 'mb_read_data':
    modbus.c:476:21: error: storage size of 'sockaddr' isn't known
         struct sockaddr sockaddr;
                         ^

### CODE REVIEW

**Comment by octo** [comment]
The *modbus plugin* now builds successfully on FreeBSD 10, but the tests still fail due to #2029.
