### ISSUE TITLE
collectd don't work with xfsprogs-4.5.0

### ISSUE THREAD

**Issue by Whissi** [collectd/collectd#1637]
When trying to compile *collectd* with *xfsprogs-4.5.0* checking for *xfs/xqm.h* fails:

```
configure:17300: checking xfs/xqm.h usability
configure:17300: x86_64-pc-linux-gnu-gcc -c -O2 -pipe -march=ivybridge -mtune=ivybridge -mno-xsaveopt  conftest.c >&5
In file included from /usr/include/xfs/xfs.h:37:0,
                 from /usr/include/xfs/xqm.h:21,
                 from conftest.c:142:
/usr/include/xfs/linux.h:145:9: error: unknown type name 'off64_t'
 typedef off64_t  xfs_off_t;
         ^
configure:17300: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "collectd"
| #define PACKAGE_TARNAME "collectd"
| #define PACKAGE_VERSION "5.5.1.git"
| #define PACKAGE_STRING "collectd 5.5.1.git"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define LT_MODULE_EXT ".so"
| #define LT_MODULE_PATH_VAR "LD_LIBRARY_PATH"
| #define LT_DLSEARCH_PATH "/lib:/usr/lib:/lib64:/usr/lib64:/usr/local/lib64:/lib32:/usr/lib32:/usr/local/lib32:/lib:/usr/lib:/usr/local/lib:/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/32:/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0:/opt/hp/hpacucli:/usr/lib64/oracle/11.2.0.4/client/lib64:/usr/lib/postgresql:/usr/lib64/postgresql:/usr/lib64/postgresql-9.5/lib64/"
| #define HAVE_LIBDL 1
| #define HAVE_DLERROR 1
| #define HAVE_LIBDLLOADER 1
| #define HAVE_ARGZ_H 1
| #define HAVE_ERROR_T 1
| #define HAVE_ARGZ_ADD 1
| #define HAVE_ARGZ_APPEND 1
| #define HAVE_ARGZ_COUNT 1
| #define HAVE_ARGZ_CREATE_SEP 1
| #define HAVE_ARGZ_INSERT 1
| #define HAVE_ARGZ_NEXT 1
| #define HAVE_ARGZ_STRINGIFY 1
| #define HAVE_WORKING_ARGZ 1
| #define HAVE_PRELOADED_SYMBOLS 1
| #define HAVE_LTDL 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DIRENT_H 1
| #define HAVE_CLOSEDIR 1
| #define HAVE_OPENDIR 1
| #define HAVE_READDIR 1
| #define LT_LIBEXT "a"
| #define LT_LIBPREFIX "lib"
| #define LIBTOOL_VERSION 2
| #define PACKAGE "collectd"
| #define VERSION "5.5.1.git"
| #define YYTEXT_POINTER 1
| #define HAVE_PROTOBUF_C_PROTOBUF_C_H 1
| #define KERNEL_LINUX 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_WAIT_H 1
| #define HAVE_DIRENT_H 1
| #define HAVE__BOOL 1
| #define HAVE_STDBOOL_H 1
| #define HAVE_STDIO_H 1
| #define HAVE_ERRNO_H 1
| #define HAVE_MATH_H 1
| #define HAVE_STDARG_H 1
| #define HAVE_SYSLOG_H 1
| #define HAVE_FCNTL_H 1
| #define HAVE_SIGNAL_H 1
| #define HAVE_ASSERT_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_SOCKET_H 1
| #define HAVE_SYS_SELECT_H 1
| #define HAVE_POLL_H 1
| #define HAVE_NETDB_H 1
| #define HAVE_ARPA_INET_H 1
| #define HAVE_SYS_RESOURCE_H 1
| #define HAVE_SYS_PARAM_H 1
| #define HAVE_REGEX_H 1
| #define HAVE_SYS_IOCTL_H 1
| #define HAVE_ENDIAN_H 1
| #define HAVE_FNMATCH_H 1
| #define HAVE_LIBGEN_H 1
| #define HAVE_NETINET_IN_SYSTM_H 1
| #define HAVE_NETINET_IN_H 1
| #define HAVE_NETINET_IP_H 1
| #define HAVE_NETINET_IP_ICMP_H 1
| #define HAVE_NETINET_IP6_H 1
| #define HAVE_NETINET_ICMP6_H 1
| #define HAVE_NETINET_TCP_H 1
| #define HAVE_NETINET_UDP_H 1
| #define HAVE_STRUCT_IP6_EXT 1
| #define HAVE_SYS_SYSCTL_H 1
| #define HAVE_LINUX_MAJOR_H 1
| #define HAVE_LINUX_RAID_MD_U_H 1
| #define HAVE_LINUX_WIRELESS_H 1
| #define HAVE_SYS_SWAP_H 1
| #define HAVE_UTMP_H 1
| #define HAVE_UTMPX_H 1
| #define HAVE_IFADDRS_H 1
| #define HAVE_NET_IF_H 1
| #define HAVE_LINUX_IF_H 1
| #define HAVE_LINUX_INET_DIAG_H 1
| #define HAVE_LINUX_NETDEVICE_H 1
| #define HAVE_LINUX_SOCKIOS_H 1
| #define HAVE_LINUX_ETHTOOL_H 1
| #define HAVE_LINUX_IP_VS_H 1
| #define HAVE_SYS_MOUNT_H 1
| #define HAVE_LINUX_UN_H 1
| #define HAVE_PWD_H 1
| #define HAVE_GRP_H 1
| #define HAVE_SYS_UN_H 1
| #define HAVE_CTYPE_H 1
| #define HAVE_LIMITS_H 1
| /* end confdefs.h.  */
| #include <stdio.h>
| #ifdef HAVE_SYS_TYPES_H
| # include <sys/types.h>
| #endif
| #ifdef HAVE_SYS_STAT_H
| # include <sys/stat.h>
| #endif
| #ifdef STDC_HEADERS
| # include <stdlib.h>
| # include <stddef.h>
| #else
| # ifdef HAVE_STDLIB_H
| #  include <stdlib.h>
| # endif
| #endif
| #ifdef HAVE_STRING_H
| # if !defined STDC_HEADERS && defined HAVE_MEMORY_H
| #  include <memory.h>
| # endif
| # include <string.h>
| #endif
| #ifdef HAVE_STRINGS_H
| # include <strings.h>
| #endif
| #ifdef HAVE_INTTYPES_H
| # include <inttypes.h>
| #endif
| #ifdef HAVE_STDINT_H
| # include <stdint.h>
| #endif
| #ifdef HAVE_UNISTD_H
| # include <unistd.h>
| #endif
| #include <xfs/xqm.h>
configure:17300: result: no
configure:17300: checking xfs/xqm.h presence
configure:17300: x86_64-pc-linux-gnu-gcc -E  conftest.c
configure:17300: $? = 0
configure:17300: result: yes
configure:17300: WARNING: xfs/xqm.h: present but cannot be compiled
configure:17300: WARNING: xfs/xqm.h:     check for missing prerequisite headers?
configure:17300: WARNING: xfs/xqm.h: see the Autoconf documentation
configure:17300: WARNING: xfs/xqm.h:     section "Present But Cannot Be Compiled"
configure:17300: WARNING: xfs/xqm.h: proceeding with the compiler's result
configure:17300: checking for xfs/xqm.h
configure:17300: result: no
```

Following http://thread.gmane.org/gmane.comp.file-systems.fstests/1981/focus=1994 it looks like we need to define *_GNU_SOURCE*.
