### ISSUE TITLE
Missing header in package on Ubuntu 20.04

### ISSUE THREAD

**Issue by ojroques** [collectd/collectd#3881]
*   Version of collectd: 5.9.0
*   Operating system / distribution: Ubuntu 20.04
*   Kernel version (if applicable): `5.4.0-73-generic`

## Details

I have developed a custom plugin for collectd that uses the `plugin.h` header. It worked fine on Ubuntu 18.04. But recently (May 2021) I've tried to recompile the plugin on Ubuntu 20.04 and it fails.

More specifically, this code does not compile anymore on Ubuntu 20.04 (I've installed the `collectd` , `collectd-core`, `collectd-dbg`, `collectd-dev`, `collectd-utils` packages but same error):

```c
#include <collectd/core/daemon/plugin.h>

int main() {}
```

```c
In file included from collectd.c:1:
/usr/include/collectd/core/daemon/plugin.h:34:10: fatal error: utils/metadata/meta_data.h: No such file or directory
   34 | #include "utils/metadata/meta_data.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

`meta_data.h` is not present in the collectd package on Ubuntu. The whole `utils` folder is not there.

**Comment by mrunge** [comment]
That sounds like a packaging issue. You may want to check with your distributor.

**Comment by ojroques** [comment]
I've opened an issue on Ubuntu bug tracker: https://bugs.launchpad.net/ubuntu/+source/collectd/+bug/1929079
