### ISSUE TITLE
Collectd 5.8.0 Solaris 11 - install fails

### ISSUE THREAD

**Issue by RedWizard75** [collectd/collectd#2984]
*   Version of collectd: 5.8.0
*   Operating system / distribution: Solaris 11.3 (SRU: 11.3.35.6.0),
*   Kernel version (if applicable): N/A

## Expected behavior

Installation instructions indicated running
# ./configure CFLAGS="-m64 -pthreads -D_POSIX_PTHREAD_SEMANTICS"
# make
# make install

## Actual behavior
I’m trying to install collectd-5.8.0 on a  it fails to ‘make’.

$ make

make  all-am

  CC       src/utils_cmds.lo

In file included from src/utils_cmds.c:30:0:

src/daemon/common.h:285:15: error: unknown type name âkstat_tâ; did you mean âfloat_tâ?

int get_kstat(kstat_t **ksp_ptr, char *module, int instance, char *name);

               ^~~~~~~

               float_t

src/daemon/common.h:286:27: error: unknown type name âkstat_tâ; did you mean âfloat_tâ?

long long get_kstat_value(kstat_t *ksp, char *name);

                           ^~~~~~~

                           float_t

*** Error code 1

The following command caused the error:

echo "  CC      " src/utils_cmds.lo;depbase=`echo src/utils_cmds.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\

/bin/sh ./libtool --silent --tag=CC    --mode=compile gcc -DHAVE_CONFIG_H  -I. -I./src  -I./src -I./src/daemon  -DPREFIX='"/opt/collectd"'  -DCONFIGFILE='"/opt/collectd/etc/collectd.conf"'  -DLOCALSTATEDIR='"/opt/collectd/var"'  -DPKGLOCALSTATEDIR='"/opt/collectd/var/lib/collectd"'  -DPLUGINDIR='"/opt/collectd/lib/collectd"'  -DPKGDATADIR='"/opt/collectd/share/collectd"'   -Wall -Werror -m64 -pthreads -D_POSIX_PTHREAD_SEMANTICS -MT src/utils_cmds.lo -MD -MP -MF $depbase.Tpo -c -o src/utils_cmds.lo src/utils_cmds.c &&\

mv -f $depbase.Tpo $depbase.Plo

make: Fatal error: Command failed for target `src/utils_cmds.lo'

Current working directory /opt/collectd-5.8.0

*** Error code 1

make: Fatal error: Command failed for target `all'

Could you please provide assistance in fixing this error? I've installed the prerequisites required in the README, upgraded Perl to 5.22, tried make and gmake too.

## Steps to reproduce

N/A - install phase.

**Comment by octo** [comment]
Can you please post the result of?:

```bash
grep kstat config.log
```

**Comment by rpv-tomsk** [comment]
We had some work on Solaris builds after 5.8.0 was released, such as #2784.
Can you please try to build collectd-5.8.1 ? That is really required step to solve this issue.
