### PR TITLE
dpdkstats: Fix compilation issue

### PR DESCRIPTION
**Pull request by vmytnykx**
Fixed dpdkstats plugin compilation issue caused by #2519 commit.

===================
  CC       src/dpdkstat_la-dpdkstat.lo
src/dpdkstat.c: In function ‘dpdk_stats_preinit’:
src/dpdkstat.c:128:10: error: unused variable ‘errbuf’ [-Werror=unused-variable]
     char errbuf[ERR_BUF_SIZE];
          ^
src/dpdkstat.c: In function ‘dpdk_stats_reinit_helper’:
src/dpdkstat.c:449:10: error: unused variable ‘errbuf’ [-Werror=unused-variable]
     char errbuf[ERR_BUF_SIZE];
          ^
cc1: all warnings being treated as errors

### CODE REVIEW

**Comment by maryamtahhan** [comment]
Ah super :D this was the issue we mentioned earlier... I will kick off CI again now

thanks

**Comment by octo** [comment]
Excellent :-) thanks for fixing!
