### ISSUE TITLE
utils_time.c: broken in master on freebsd since 349d1538

### ISSUE THREAD

**Issue by mfournier** [collectd/collectd#1443]
@octo, I just noticed this error which goes away when reverting 349d1538:
```
utils_time.c:91:22: error: invalid operands to binary expression ('char *(*)(int, int)' and 'int')
  minutes = timezone / 60;
```

This doesn't happen on linux apparently, I noticed it on FreeBSD here:
https://ci.collectd.org/job/master-build-on-freebsd10-amd64-with-default-toolchain/124//console

I also discovered that unlike on linux distros, FreeBSD's `make -k` always returns 0. This explains why jenkins didn't catch this error. I'll change the job config to avoid this problem.

**Comment by octo** [comment]
Meh, it appears that FreeBSD defines `timezone` as
```c
char *timezone (int, int);
```
while [X/Open](http://pubs.opengroup.org/onlinepubs/9699919799/functions/tzset.html) defines it as:
```c
extern long timezone;
```

My guess would be that we need some preprocessor define to enable X/Open compliance …

**Comment by mfournier** [comment]
Fixed with 92ba2e344 and https://github.com/collectd/collectd-ci/commit/2234aa66.

Thanks @octo !
